server:
  port: 88
  #==================================spring==================================
spring:
  application:
    name: blog
  #================mysql==============================
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #================redis==============================
  redis:
    host: 192.168.133.248
    port: 6379
  #================mail==============================
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 2625727808@qq.com
    password: zfdsdfsrvgdhdeod  #个人邮箱key
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: true
          auth: true
        debug: true


  #================mongoDB=========================
  data:
    mongodb:
      uri: mongodb://192.168.133.248:27017/blog

   #================swagger=========================

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

   #================文件上传=========================

  servlet:
    multipart:
      #总上传数据大小
      max-request-size: 10MB
#      单个文件大小
      max-file-size: 5MB
#      开启文件上传
      enabled: true

  #===============================spring====================================

  #================mybatis-plus=========================

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  #================mybatis-plus=========================
#debug: true